class Field:
    username_textfield = "//input[@id='user-name']"
    username_passwordfield = "//input[@id='password']"
    login_button = "//input[@id='login-button']"
    product_span = "//span[@class='title']"
    products_sort_order_combobox = "//select[@class='product_sort_container']"
    # sort options
    sort_az_option = "//option[@value='az']"
    sort_za_option = "//option[@value='za']"
    sort_lohi_option = "//option[@value='lohi']"
    sort_hilo_option = "//option[@value='hilo']"
    sort_active_option = "//span[@class='active_option']"
    # add product buttons
    add_product_btn1 = "//button[@id='add-to-cart-sauce-labs-fleece-jacket']"
    add_product_btn2 = "//button[@id='add-to-cart-sauce-labs-backpack']"
    add_product_btn3 = "//button[@id='add-to-cart-sauce-labs-bolt-t-shirt']"
    # go to cart
    goto_cart_link = "//a[@class='shopping_cart_link']"
    cart_span = "//span[@class='title']"
    product1_name_div = "//div[normalize-space()='Sauce Labs Fleece Jacket']"
    product2_name_div = "//div[normalize-space()='Sauce Labs Backpack']"
    product3_name_div = "//div[normalize-space()='Sauce Labs Bolt T-Shirt']"
    # checkout order
    checkout_btn = "//button[@id='checkout']"
    order_firstname_input = "//input[@id='first-name']"
    order_lastname_input = "//input[@id='last-name']"
    order_postalcode_input = "//input[@id='postal-code']"
    continue_btn = "//input[@id='continue']"
    # checkout overview
    overview_span = "//span[@class='title']"
    overview_item1_price_div = "//div[@class='inventory_item_price'][normalize-space()='$49.99']"
    overview_item2_price_div = "//div[@class='inventory_item_price'][normalize-space()='$29.99']"
    overview_item3_price_div = "//div[@class='inventory_item_price'][normalize-space()='$15.99']"
    overview_total_price_lbl = "//div[@class='summary_total_label']"
    overview_tax_lbl = "//div[@class='summary_tax_label']"
    overview_item_price_lbl = "//div[@class='summary_subtotal_label']"
    overview_finish_btn = "//button[@id='finish']"
    order_complete_header = "//h2[normalize-space()='THANK YOU FOR YOUR ORDER']"
    # products details
    cart_item_div = "//div[@class='cart_item']"
    cart_item_name_div = "//div[@class='cart_item'][%d]//div[@class='inventory_item_name']"
    cart_item_quantity_div = "//div[@class='cart_item'][%d]//div[@class='cart_quantity']"
    cart_item_price_div = "//div[@class='cart_item'][%d]//div[@class='inventory_item_price']"